services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizoo_user
      POSTGRES_PASSWORD: quizoo_pass
      POSTGRES_DB: quizoo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
